version: "3.8"

services:
    start_page:
        volumes:
            - type: bind
              source: .
              target: /app
        build:
            dockerfile: Dockerfile
        command: bash -c "cd app && trunk serve --address 0.0.0.0"
        environment:
            - TRUNK_SERVE_PORT=8080
        ports:
            - "8080:8080"
